package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// runDeploy provisions the operator-side bits that are NOT the binary itself
// (the binary arrives via `go install` and is already on PATH). It does not
// generate settings.json — that is materialized by `dispatch` at startup with
// the runtime paths. It writes an example config, sanity-checks that the binary
// can find itself on PATH (the hook is referenced by bare name), and — with
// --workdir — provisions $workdir/{project,state} and marks project trusted.
func runDeploy(args []string) {
	fs := flag.NewFlagSet("deploy", flag.ContinueOnError)
	conf := fs.String("conf", "", "directory to write bot.toml.example into")
	workdir := fs.String("workdir", "", "provision a static workdir: create $workdir/{project,state} and mark $workdir/project trusted in ~/.claude.json (the same trust dispatch sets at startup)")
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}

	// The responder invokes `ak-tgclaude send` by bare name, so the ak-tgclaude on
	// PATH must be this binary. `dispatch` enforces this (fail-fast); here it is
	// only a provisioning hint, so a mismatch is a warning, not an error.
	if err := checkBinaryOnPath(); err != nil {
		fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: warning: %v\n", err)
	} else {
		fmt.Println("ak-tgclaude: deploy: ak-tgclaude on PATH is this binary")
	}

	if *conf != "" {
		if err := os.MkdirAll(*conf, 0o700); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		dest := filepath.Join(*conf, "bot.toml.example")
		if err := os.WriteFile(dest, []byte(exampleConfig), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("ak-tgclaude: deploy: wrote %s\n", dest)
	}

	if *workdir != "" {
		wd := resolvePath(*workdir)
		if err := validatePath("workdir", wd); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(2)
		}
		project := filepath.Join(wd, "project")
		state := filepath.Join(wd, "state")
		for _, d := range []string{project, state} {
			if err := os.MkdirAll(d, 0o700); err != nil {
				fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
				os.Exit(1)
			}
		}
		fmt.Printf("ak-tgclaude: deploy: provisioned %s (project/ + state/)\n", wd)
		// Non-fatal like dispatch: a trust hiccup should not fail provisioning; the
		// responder still runs (untrusted), and the next dispatch start retries.
		if err := markProjectTrusted(project); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: warning: marking %s trusted: %v\n", project, err)
		} else {
			fmt.Printf("ak-tgclaude: deploy: marked %s trusted in ~/.claude.json\n", project)
		}
	}

	fmt.Println("ak-tgclaude: deploy: settings.json is generated by `dispatch` at startup")
}

// exampleConfig is the minimal config emitted by `deploy --conf`.
const exampleConfig = `# ak-tgclaude bot configuration (TOML). Copy to bot.toml and fill in.
bot_token = "123456789:AA...replace-me..."
profile   = "qa"
project   = "~/code/example-project"
# responder = "claude"   # or "stub" to smoke-test Telegram I/O without a model
# wire_skills = ["~/lib/my-domain-skill"]  # domain skill DIR, preloaded into the responder (always in context)
# add_skills  = ["~/lib/some-generic-skill"]  # generic skill DIR(s), copied verbatim for on-demand use (not preloaded)
# add_agents  = ["~/lib/some-agent.md"]        # generic agent .md FILE(s), copied verbatim as on-demand subagents
# deny_reads  = ["~/code/myproject/secrets.env"]  # extra paths the responder must never read
# deny_envs   = ["MY_SECRET_TOKEN"]            # extra env-var NAMES to scrub (ANTHROPIC keys are always scrubbed)
`
