package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// runDeploy provisions the operator-side bits that are NOT the binary itself
// (the binary arrives via `go install` and is already on PATH). It does not
// generate settings.json — that is materialized by `dispatch` at startup with
// the runtime paths. For now it writes an example config and sanity-checks that
// the binary can find itself on PATH (the hook is referenced by bare name).
func runDeploy(args []string) {
	fs := flag.NewFlagSet("deploy", flag.ContinueOnError)
	conf := fs.String("conf", "", "directory to write bot.toml.example into")
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}

	// The generated settings.json references the hook by bare name
	// ("ak-tgclaude hook pretooluse"), so the binary must be resolvable on PATH.
	if _, err := exec.LookPath("ak-tgclaude"); err != nil {
		fmt.Fprintln(os.Stderr, "ak-tgclaude: deploy: warning: 'ak-tgclaude' is not on PATH; "+
			"install it (e.g. `go install`) so the responder's hook command resolves")
	} else {
		fmt.Println("ak-tgclaude: deploy: found ak-tgclaude on PATH")
	}

	if *conf != "" {
		if err := os.MkdirAll(*conf, 0o700); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		dest := filepath.Join(*conf, "bot.toml.example")
		if err := os.WriteFile(dest, []byte(exampleConfig), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("ak-tgclaude: deploy: wrote %s\n", dest)
	}

	fmt.Println("ak-tgclaude: deploy: settings.json is generated by `dispatch` at startup")
}

// exampleConfig is the minimal config emitted by `deploy --conf`.
const exampleConfig = `# ak-tgclaude bot configuration (TOML). Copy to bot.toml and fill in.
bot_token = "123456789:AA...replace-me..."
profile   = "qa"
project   = "~/code/example-project"
# responder = "claude"   # or "stub" to smoke-test Telegram I/O without a model
`
