package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// runDeploy provisions the operator-side bits that are NOT the binary itself
// (the binary arrives via `go install` and is already on PATH). It does not
// generate settings.json — that is materialized by `dispatch` at startup with
// the runtime paths. For now it writes an example config and sanity-checks that
// the binary can find itself on PATH (the hook is referenced by bare name).
func runDeploy(args []string) {
	fs := flag.NewFlagSet("deploy", flag.ContinueOnError)
	conf := fs.String("conf", "", "directory to write bot.toml.example into")
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}

	// The responder invokes `ak-tgclaude send` by bare name, so the ak-tgclaude on
	// PATH must be this binary. `dispatch` enforces this (fail-fast); here it is
	// only a provisioning hint, so a mismatch is a warning, not an error.
	if err := checkBinaryOnPath(); err != nil {
		fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: warning: %v\n", err)
	} else {
		fmt.Println("ak-tgclaude: deploy: ak-tgclaude on PATH is this binary")
	}

	if *conf != "" {
		if err := os.MkdirAll(*conf, 0o700); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		dest := filepath.Join(*conf, "bot.toml.example")
		if err := os.WriteFile(dest, []byte(exampleConfig), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "ak-tgclaude: deploy: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("ak-tgclaude: deploy: wrote %s\n", dest)
	}

	fmt.Println("ak-tgclaude: deploy: settings.json is generated by `dispatch` at startup")
}

// exampleConfig is the minimal config emitted by `deploy --conf`.
const exampleConfig = `# ak-tgclaude bot configuration (TOML). Copy to bot.toml and fill in.
bot_token = "123456789:AA...replace-me..."
profile   = "qa"
project   = "~/code/example-project"
# responder = "claude"   # or "stub" to smoke-test Telegram I/O without a model
# wire_skills = ["~/lib/my-domain-skill"]  # skill(s) preloaded into the responder for domain knowledge
`
